version: '3.1'

services:

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: everycheese
      POSTGRES_USER: everycheese
      POSTGRES_DB: everycheese

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080